name: carrot_pilot_manager
description: A CarrotLink App
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dartssh2: ^2.5.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  xterm: ^4.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  video_player: ^2.8.1
  chewie: ^1.7.1
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  google_sign_in: ^6.2.1
  googleapis: ^13.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
